### ISSUE TITLE
Error in loading a file

### ISSUE THREAD

**Issue by Deduction42** [queryverse/ParquetFiles.jl#9]
I was able to get a file to read easily using Python and Pandas, however in Julia, the same file produces the following error:

ERROR: LoadError: Base.Meta.ParseError("extra token \"Vector\" after end of expression")

I usied Parquet.jl to try and load the file, and I get the following schema

Schema:
    required schema {
      optional INT64 timestamp# (from TIMESTAMP_MILLIS)  {
        optional INT64 t_datetime# (from TIMESTAMP_MILLIS)  {
          optional BYTE_ARRAY id_string# (from UTF8)  {
            optional DOUBLE v_double {
              optional DOUBLE q_double {
                optional BYTE_ARRAY alias_string# (from UTF8)  {

However when I try  to implement
schema(JuliaConverter(Main), Pq, :Tags)

I get the same error as before.

**Comment by davidanthoff** [comment]
Ideally, could you open this issue over at https://github.com/JuliaIO/Parquet.jl? This package here just uses Parquet.jl under the hood, so this kind of bug needs to be fixed over there.
